trigger:
- main

pool:
  name: Default

steps:
- script: echo 'one line run'
  displayName: 'running first maven application'
- script: mvn clean install
  displayName: 'Build'
- script: java -jar target/My-1.0-SNAPSHOT.jar
  displayName: 'Run Application'
